name: pubsec_dependecy_sorter
version: 0.0.1
description: A new Flutter package project.
environment: 
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  logger: ^1.1.0
  pubspec: ^2.3.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter: null
